
CREATE TABLE "KOMMUNE" (
  "Kommunenummer" varchar(4) PRIMARY KEY,
  "Navn" varchar(100) NOT NULL
);

CREATE TABLE "EIENDOM" (
  "EiendomId" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Kommunenummer" varchar(4) NOT NULL,
  "Gaardsnummer" int NOT NULL,
  "Bruksnummer" int NOT NULL,
  "Festenummer" int DEFAULT 0,                   
  "Seksjonsnummer" int DEFAULT 0,                 
  "Andelsnummer" int DEFAULT 0,                  
  "Adresse" varchar(200),
  "Postnummer" varchar(4),
  "Poststed" varchar(100)
);

CREATE TABLE "BYGNING" (
  "Bygningsnummer" varchar(50) PRIMARY KEY,
  "EiendomId" int NOT NULL,
  "Seksjonsnummer" int,               
  "Bygningskategori" varchar(10),
  "Byggeaar" int,
  "Materialvalg" varchar(100)
);

CREATE TABLE "ENERGIMERKE" (
  "Attestnummer" varchar(50) PRIMARY KEY,
  "Bygningsnummer" varchar(50) NOT NULL,
  "Utstedelsesdato" date NOT NULL,      
  "TypeRegistrering" varchar(50),
  "Energikarakter" varchar(1) NOT NULL,
  "Oppvarmingskarakter" varchar(10) NOT NULL,
  "BeregnetLevertEnergiTotaltKwhM2" decimal(10,2),
  "BeregnetFossilandel" decimal(5,2),
  "HarEnergiVurdering" boolean NOT NULL DEFAULT false,
  "EnergiVurderingDato" date
);

CREATE TABLE "ENERGIKARAKTER" (
  "Bokstav" varchar(1) PRIMARY KEY,
  "Beskrivelse" varchar(100) NOT NULL
);

CREATE TABLE "OPPVARMINGSKARAKTER" (
  "Kode" varchar(10) PRIMARY KEY,
  "Beskrivelse" varchar(100) NOT NULL
);

-- 2. Partial unique indexes (riktig for matrikkel-matching med Geonorge)

CREATE UNIQUE INDEX uq_matrikkel_hoved 
ON EIENDOM ("Kommunenummer", "Gaardsnummer", "Bruksnummer")
WHERE "Festenummer" IS NULL 
  AND "Seksjonsnummer" IS NULL 
  AND "Andelsnummer" IS NULL;

CREATE UNIQUE INDEX uq_matrikkel_seksjon 
ON EIENDOM ("Kommunenummer", "Gaardsnummer", "Bruksnummer", "Seksjonsnummer")
WHERE "Seksjonsnummer" IS NOT NULL;

CREATE UNIQUE INDEX uq_matrikkel_andel 
ON EIENDOM ("Kommunenummer", "Gaardsnummer", "Bruksnummer", "Andelsnummer")
WHERE "Andelsnummer" IS NOT NULL;

CREATE UNIQUE INDEX uq_matrikkel_feste 
ON EIENDOM ("Kommunenummer", "Gaardsnummer", "Bruksnummer", "Festenummer")
WHERE "Festenummer" IS NOT NULL;


COMMENT ON COLUMN "KOMMUNE"."Kommunenummer" IS '4 sifre, alltid med leading zero (f.eks. 0301)';
COMMENT ON COLUMN "EIENDOM"."Kommunenummer" IS 'FK til KOMMUNE';
COMMENT ON COLUMN "EIENDOM"."Postnummer" IS '4 sifre';
COMMENT ON COLUMN "BYGNING"."Bygningsnummer" IS 'unik nasjonal ID';
COMMENT ON COLUMN "BYGNING"."EiendomId" IS 'FK til EIENDOM';
COMMENT ON COLUMN "BYGNING"."Bygningskategori" IS 'f.eks. 111 = enebolig';
COMMENT ON COLUMN "ENERGIMERKE"."Attestnummer" IS 'unik per attest fra Enova';
COMMENT ON COLUMN "ENERGIMERKE"."Bygningsnummer" IS 'FK til BYGNING';
COMMENT ON COLUMN "ENERGIKARAKTER"."Bokstav" IS 'A–G';
COMMENT ON COLUMN "OPPVARMINGSKARAKTER"."Kode" IS '1–3';

-- 4. Fremmednøkler
ALTER TABLE "EIENDOM" 
  ADD CONSTRAINT fk_eiendom_kommune
  FOREIGN KEY ("Kommunenummer") REFERENCES "KOMMUNE" ("Kommunenummer");

ALTER TABLE "BYGNING" 
  ADD CONSTRAINT fk_bygning_eiendom
  FOREIGN KEY ("EiendomId") REFERENCES "EIENDOM" ("EiendomId");

ALTER TABLE "ENERGIMERKE" 
  ADD CONSTRAINT fk_energimerke_bygning
  FOREIGN KEY ("Bygningsnummer") REFERENCES "BYGNING" ("Bygningsnummer");

ALTER TABLE "ENERGIMERKE" 
  ADD CONSTRAINT fk_energimerke_energikarakter
  FOREIGN KEY ("Energikarakter") REFERENCES "ENERGIKARAKTER" ("Bokstav");

ALTER TABLE "ENERGIMERKE" 
  ADD CONSTRAINT fk_energimerke_oppvarmingskarakter
  FOREIGN KEY ("Oppvarmingskarakter") REFERENCES "OPPVARMINGSKARAKTER" ("Kode");